Repository prgrms-be-devcourse/NBE3-4-2-Team9, pull requests merged in 2025-02, with the labels that each got.

#26 [FIX] : U-02 #25
  backend/src/main/java/com/backend/domain/user/controller/ApiV1UserController.java
  backend/src/main/java/com/backend/global/security/SecurityConfig.java
  backend/src/main/java/com/backend/global/security/handler/OAuth2LoginFailureHandler.java
  backend/src/main/java/com/backend/global/security/handler/OAuth2LoginSuccessHandler.java
  backend/src/main/java/com/backend/global/security/oauth/CustomOAuth2UserService.java
  backend/src/main/java/com/backend/standard/util/JwtUtil.java
  backend/src/test/java/com/backend/CategoryControllerTest.java
  backend/src/test/java/com/backend/global/redis/TestRedisConfig.java
  backend/src/test/java/com/backend/global/security/handler/OAuth2LoginSuccessHandlerTest.java
  backend/src/test/java/com/backend/global/security/oauth/CustomOAuth2UserServiceTest.java
  backend/src/test/java/com/backend/global/security/oauth/OAuth2AuthenticationTest.java
  backend/src/test/resources/application-test.yml
Labels: bug

#33 [FEAT] J-01
  backend/src/main/java/com/backend/domain/jobposting/entity/ExperienceLevel.java
  backend/src/main/java/com/backend/domain/jobposting/entity/JobPosting.java
  backend/src/main/java/com/backend/domain/jobposting/entity/JobPostingStatus.java
  backend/src/main/java/com/backend/domain/jobposting/entity/RequireEducate.java
  backend/src/main/java/com/backend/domain/jobposting/entity/Salary.java
  backend/src/main/java/com/backend/domain/jobposting/repository/JobPostingJpaRepository.java
  backend/src/main/java/com/backend/domain/jobposting/repository/JobPostingRepository.java
  backend/src/main/java/com/backend/domain/jobposting/repository/JobPostingRepositoryImpl.java
  backend/src/main/java/com/backend/domain/jobskill/entity/JobSkill.java
  backend/src/main/java/com/backend/domain/jobskill/repository/JobSkillJpaRepository.java
  backend/src/main/java/com/backend/domain/jobskill/repository/JobSkillRepository.java
  backend/src/main/java/com/backend/domain/jobskill/repository/JobSkillRepositoryImpl.java
Labels: enhancement

#29 [FEAT] U-04 #27
  backend/src/main/java/com/backend/domain/user/controller/ApiV1UserController.java
  backend/src/main/java/com/backend/domain/user/service/UserService.java
  backend/src/main/java/com/backend/global/security/SecurityConfig.java
  backend/src/test/java/com/backend/domain/user/ApiV1UserControllerTest.java
  backend/src/test/java/com/backend/global/annotation/CustomWithMock.java
  backend/src/test/java/com/backend/global/config/CustomWithSecurityContextFactory.java
Labels: enhancement

#28 [FEAT] CG-02 #23
  backend/src/main/java/com/backend/domain/category/controller/CategoryController.java
  backend/src/main/java/com/backend/domain/category/converter/CategoryConverter.java
  backend/src/main/java/com/backend/domain/category/dto/response/CategoryResponse.java
  backend/src/main/java/com/backend/domain/category/entity/Category.java
  backend/src/main/java/com/backend/domain/category/repository/CategoryRepository.java
  backend/src/main/java/com/backend/domain/category/service/CategoryService.java
  backend/src/main/java/com/backend/domain/user/entity/UserRole.java
  backend/src/main/java/com/backend/global/exception/GlobalErrorCode.java
  backend/src/main/java/com/backend/global/security/SecurityConfig.java
  backend/src/main/java/com/backend/global/security/custom/CustomUserDetails.java
  backend/src/test/java/com/backend/CategoryControllerTest.java
  backend/src/test/java/com/backend/global/category/CategoryControllerTest.java
  backend/src/test/java/com/backend/global/category/CategoryServiceTest.java
Labels: enhancement

#38 [FEAT]: U-05 #34
  backend/src/main/java/com/backend/domain/jobskill/entity/JobSkill.java
  backend/src/main/java/com/backend/domain/jobskill/repository/JobSkillJpaRepository.java
  backend/src/main/java/com/backend/domain/jobskill/repository/JobSkillRepository.java
  backend/src/main/java/com/backend/domain/jobskill/repository/JobSkillRepositoryImpl.java
  backend/src/main/java/com/backend/domain/user/controller/ApiV1UserController.java
  backend/src/main/java/com/backend/domain/user/dto/request/JobSkillRequest.java
  backend/src/main/java/com/backend/domain/user/dto/request/UserModifyProfileRequest.java
  backend/src/main/java/com/backend/domain/user/dto/response/JobSkillResponse.java
  backend/src/main/java/com/backend/domain/user/dto/response/UserGetProfileResponse.java
  backend/src/main/java/com/backend/domain/user/entity/SiteUser.java
  backend/src/main/java/com/backend/domain/user/service/UserService.java
  backend/src/main/java/com/backend/global/baseentity/BaseInitData.java
  backend/src/main/java/com/backend/global/exception/GlobalErrorCode.java
  backend/src/main/java/com/backend/global/security/SecurityConfig.java
  backend/src/test/java/com/backend/domain/user/ApiV1UserControllerTest.java
Labels: enhancement

#44 [FEAT] CG-03 #35
  backend/src/main/java/com/backend/domain/category/controller/CategoryController.java
  backend/src/main/java/com/backend/domain/category/converter/CategoryConverter.java
  backend/src/main/java/com/backend/domain/category/dto/response/CategoryResponse.java
  backend/src/main/java/com/backend/domain/category/entity/Category.java
  backend/src/main/java/com/backend/domain/category/repository/CategoryRepository.java
  backend/src/main/java/com/backend/domain/category/service/CategoryService.java
  backend/src/main/java/com/backend/domain/user/entity/UserRole.java
  backend/src/main/java/com/backend/global/exception/GlobalErrorCode.java
  backend/src/main/java/com/backend/global/security/SecurityConfig.java
  backend/src/test/java/com/backend/domain/category/CategoryControllerTest.java
  backend/src/test/java/com/backend/domain/category/CategoryServiceTest.java
  backend/src/test/java/com/backend/domain/category/TestSecurityConfig.java
Labels: enhancement

#43 Feature/J-01
  backend/build.gradle
  backend/src/main/java/com/backend/domain/jobposting/controller/ApiV1JobPostingController.java
  backend/src/main/java/com/backend/domain/jobposting/dto/JobPostingDetailResponse.java
  backend/src/main/java/com/backend/domain/jobposting/dto/JobPostingPageResponse.java
  backend/src/main/java/com/backend/domain/jobposting/entity/JobPosting.java
  backend/src/main/java/com/backend/domain/jobposting/entity/RequireEducate.java
  backend/src/main/java/com/backend/domain/jobposting/repository/JobPostingQueryRepository.java
  backend/src/main/java/com/backend/domain/jobposting/repository/JobPostingRepository.java
  backend/src/main/java/com/backend/domain/jobposting/repository/JobPostingRepositoryImpl.java
  backend/src/main/java/com/backend/domain/jobposting/service/JobPostingService.java
  backend/src/main/java/com/backend/domain/jobposting/util/JobPostingSearchCondition.java
  backend/src/main/java/com/backend/domain/jobskill/dto/JobSkillResponse.java
  backend/src/main/java/com/backend/domain/user/dto/response/JobSkillResponse.java
  backend/src/main/java/com/backend/domain/user/dto/response/UserGetProfileResponse.java
  backend/src/main/java/com/backend/global/config/QuerydslConfig.java
  backend/src/main/java/com/backend/global/security/SecurityConfig.java
  backend/src/test/java/com/backend/domain/jobposting/ApiV1JobPostingControllerTest.java
Labels: enhancement

#50 Feature/G-06
  backend/src/main/java/com/backend/domain/category/controller/CategoryController.java
  backend/src/test/java/com/backend/domain/category/CategoryServiceTest.java
  backend/src/test/java/com/backend/domain/jobposting/ApiV1JobPostingControllerTest.java
  backend/src/test/resources/sql/delete.sql
  backend/src/test/resources/sql/init.sql
Labels: enhancement

#49 [FEAT] U-01
  backend/src/main/java/com/backend/domain/user/dto/response/KakaoLoginResponse.java
  backend/src/main/java/com/backend/global/config/AppConfig.java
  backend/src/main/java/com/backend/global/exception/GlobalErrorCode.java
  backend/src/main/java/com/backend/global/security/SecurityConfig.java
  backend/src/main/java/com/backend/global/security/filter/JwtAuthorizationFilter.java
  backend/src/main/java/com/backend/global/security/handler/OAuth2LoginSuccessHandler.java
  backend/src/main/java/com/backend/standard/util/JwtUtil.java
  backend/src/test/java/com/backend/domain/category/CategoryControllerTest.java
  backend/src/test/java/com/backend/domain/jobposting/ApiV1JobPostingControllerTest.java
  backend/src/test/java/com/backend/domain/user/ApiV1UserControllerTest.java
  backend/src/test/java/com/backend/global/security/JwtUtilTest.java
  backend/src/test/java/com/backend/global/security/handler/OAuth2LoginSuccessHandlerTest.java
  frontend/eslint.config.mjs
  frontend/next.config.js
  frontend/next.config.ts
  frontend/package-lock.json
  frontend/package.json
  frontend/postcss.config.js
  frontend/postcss.config.mjs
  frontend/public/file.svg
  frontend/public/globe.svg
  frontend/public/next.svg
  frontend/public/vercel.svg
  frontend/public/window.svg
  frontend/src/app/admin/login/page.tsx
  frontend/src/app/admin/profile/page.tsx
  frontend/src/app/favicon.ico
  frontend/src/app/globals.css
  frontend/src/app/layout.tsx
  frontend/src/app/login/oauth2/code/kakao/page.tsx
  frontend/src/app/login/page.tsx
  frontend/src/app/page.tsx
  frontend/src/app/users/[id]/page.tsx
  frontend/src/components/Header.tsx
  frontend/src/components/KakaoIcon.tsx
  frontend/src/components/RootLayoutClient.tsx
  frontend/src/store/features/authSlice.ts
  frontend/src/store/store.ts
  frontend/tailwind.config.ts
  frontend/tsconfig.json
Labels: enhancement, bug, frontend, layout

#54 [FEAT] [FE] : U-01 ~ U-05
  backend/src/main/java/com/backend/global/security/SecurityConfig.java
  frontend/src/app/users/[id]/edit/page.tsx
  frontend/src/app/users/[id]/page.tsx
  frontend/src/components/Header.tsx
Labels: frontend, layout

#57 [FEAT] [FE]: J-00FE
  frontend/next.config.js
  frontend/package-lock.json
  frontend/package.json
  frontend/src/api/axios.ts
  frontend/src/api/jobPosting.ts
  frontend/src/api/post.ts
  frontend/src/app/job-posting/[id]/page.tsx
  frontend/src/app/layout.tsx
  frontend/src/app/page.tsx
  frontend/src/app/post/page.tsx
  frontend/src/components/Providers.tsx
  frontend/src/components/job/JobPostingCard.tsx
  frontend/src/types/job-posting/JobPostingPageResponse.ts
  frontend/src/types/post/PostResponse.ts
  frontend/src/utils/dateUtils.ts
Labels: frontend, layout

#63 [FEAT] [FE] : J-00FE
  frontend/next.config.js
  frontend/src/api/axios.ts
  frontend/src/api/category.ts
  frontend/src/api/post.ts
  frontend/src/app/page.tsx
  frontend/src/app/post/[id]/page.tsx
  frontend/src/app/post/page.tsx
  frontend/src/app/post/write/page.tsx
  frontend/src/types/post/Category.ts
  frontend/src/types/post/PostResponse.ts
Labels: frontend, layout

#56 [FEAT] CH-01 #16
  backend/.gitignore
  backend/build.gradle
  backend/src/main/java/com/backend/domain/chat/controller/ChatControllerV1.java
  backend/src/main/java/com/backend/domain/chat/controller/WebSocketEventController.java
  backend/src/main/java/com/backend/domain/chat/dto/request/ChatRequest.java
  backend/src/main/java/com/backend/domain/chat/dto/response/ChatResponse.java
  backend/src/main/java/com/backend/domain/chat/dto/response/ChatResponses.java
  backend/src/main/java/com/backend/domain/chat/dto/response/ChatsInPost.java
  backend/src/main/java/com/backend/domain/chat/entity/Chat.java
  backend/src/main/java/com/backend/domain/chat/entity/MessageType.java
  backend/src/main/java/com/backend/domain/chat/exception/WebSocketException.java
  backend/src/main/java/com/backend/domain/chat/handler/StompHandler.java
  backend/src/main/java/com/backend/domain/chat/handler/WebSocketEventListener.java
  backend/src/main/java/com/backend/domain/chat/mapper/ChatMapper.java
  backend/src/main/java/com/backend/domain/chat/repository/ChatRepository.java
  backend/src/main/java/com/backend/domain/chat/service/ChatService.java
  backend/src/main/java/com/backend/global/baseentity/BaseInitData.java
  backend/src/main/java/com/backend/global/config/WebSocketConfig.java
  backend/src/main/java/com/backend/global/exception/GlobalErrorCode.java
  backend/src/main/java/com/backend/global/security/SecurityConfig.java
  backend/src/main/java/com/backend/standard/util/ExtractUtil.java
  backend/src/main/java/com/backend/standard/util/JwtUtil.java
  backend/src/main/resources/templates/index.html
  backend/src/test/java/com/backend/domain/chat/ChatControllerTest.java
  backend/src/test/java/com/backend/domain/chat/util/ChatObjectProvider.java
  backend/src/test/resources/sql/delete.sql
  backend/src/test/resources/sql/init.sql
Labels: enhancement

#66 [FEAT] [FE] : B-01FE #64
  frontend/src/api/auth.ts
  frontend/src/app/admin/login/page.tsx
  frontend/src/app/admin/page.tsx
  frontend/src/app/admin/profile/page.tsx
  frontend/src/components/common/Navbar.tsx
  frontend/src/middleware.ts
  frontend/src/types/auth/AuthResponse.ts
  frontend/src/types/auth/AuthState.ts
Labels: frontend, layout

#60 [FEAT] B-03 #37
  backend/src/main/java/com/backend/domain/post/controller/ApiV1PostController.java
  backend/src/main/java/com/backend/domain/post/dto/PostCreateRequestDto.java
  backend/src/main/java/com/backend/domain/post/dto/PostResponseDto.java
  backend/src/main/java/com/backend/domain/post/entity/Post.java
  backend/src/main/java/com/backend/domain/post/service/PostService.java
  backend/src/main/java/com/backend/global/aspect/ResponseAspect.java
  backend/src/main/java/com/backend/global/exception/GlobalErrorCode.java
  backend/src/main/java/com/backend/global/security/SecurityConfig.java
  backend/src/test/java/com/backend/domain/post/PostControllerTest.java
  backend/src/test/java/com/backend/domain/post/PostRepositoryTest.java
  backend/src/test/resources/sql/init.sql
Labels: enhancement

#59 [FEAT] CG-03 #35
  backend/src/main/generated/com/backend/domain/category/entity/QCategory.java
  backend/src/main/generated/com/backend/domain/jobposting/dto/QJobPostingPageResponse.java
  backend/src/main/generated/com/backend/domain/jobposting/entity/QExperienceLevel.java
  backend/src/main/generated/com/backend/domain/jobposting/entity/QJobPosting.java
  backend/src/main/generated/com/backend/domain/jobposting/entity/QRequireEducate.java
  backend/src/main/generated/com/backend/domain/jobposting/entity/QSalary.java
  backend/src/main/generated/com/backend/domain/jobskill/entity/QJobSkill.java
  backend/src/main/generated/com/backend/domain/post/entity/QPost.java
  backend/src/main/generated/com/backend/domain/user/entity/QSiteUser.java
  backend/src/main/generated/com/backend/global/baseentity/QBaseEntity.java
  backend/src/main/java/com/backend/domain/category/controller/CategoryController.java
  backend/src/main/java/com/backend/domain/category/converter/CategoryConverter.java
  backend/src/main/java/com/backend/domain/category/dto/request/CategoryRequest.java
  backend/src/main/java/com/backend/domain/category/entity/Category.java
  backend/src/main/java/com/backend/domain/category/repository/CategoryRepository.java
  backend/src/main/java/com/backend/domain/category/service/CategoryService.java
  backend/src/main/java/com/backend/global/advice/GlobalControllerAdvice.java
  backend/src/main/java/com/backend/global/exception/GlobalErrorCode.java
  backend/src/main/java/com/backend/global/security/SecurityConfig.java
  backend/src/main/java/com/backend/global/security/custom/CustomUserDetails.java
  backend/src/test/java/com/backend/domain/category/CategoryControllerTest.java
  backend/src/test/java/com/backend/domain/category/CategoryServiceTest.java
  backend/src/test/java/com/backend/domain/category/TestSecurityConfig.java
  backend/src/test/java/com/backend/domain/post/PostRepositoryTest.java
  backend/src/test/resources/application-test.yml
  backend/src/test/resources/sql/delete.sql
  backend/src/test/resources/sql/init.sql
Labels: enhancement

#65 Feature/J-03
  backend/.gitignore
  backend/build.gradle
  backend/src/main/java/com/backend/domain/jobposting/dto/JobPostingDetailResponse.java
  backend/src/main/java/com/backend/domain/jobposting/entity/JobPosting.java
  backend/src/main/java/com/backend/domain/jobposting/entity/JobPostingJobSkill.java
  backend/src/main/java/com/backend/domain/jobposting/repository/JobPostingJpaRepository.java
  backend/src/main/java/com/backend/domain/jobposting/repository/JobPostingRepository.java
  backend/src/main/java/com/backend/domain/jobposting/repository/JobPostingRepositoryImpl.java
  backend/src/main/java/com/backend/domain/like/controller/ApiV1LikeController.java
  backend/src/main/java/com/backend/domain/like/domain/LikeType.java
  backend/src/main/java/com/backend/domain/like/dto/LikeCreateRequest.java
  backend/src/main/java/com/backend/domain/like/dto/LikeCreateResponse.java
  backend/src/main/java/com/backend/domain/like/entity/Like.java
  backend/src/main/java/com/backend/domain/like/repository/LikeJpaRepository.java
  backend/src/main/java/com/backend/domain/like/repository/LikeRepository.java
  backend/src/main/java/com/backend/domain/like/repository/LikeRepositoryImpl.java
  backend/src/main/java/com/backend/domain/like/service/LikeService.java
  backend/src/main/java/com/backend/domain/post/controller/ApiV1PostController.java
  backend/src/main/java/com/backend/global/aspect/ResponseAspect.java
  backend/src/main/java/com/backend/global/baseentity/BaseInitData.java
  backend/src/main/java/com/backend/global/exception/GlobalErrorCode.java
  backend/src/main/java/com/backend/global/security/SecurityConfig.java
  backend/src/main/java/com/backend/global/validator/EnumValidator.java
  backend/src/main/java/com/backend/global/validator/ValidEnum.java
  backend/src/test/java/com/backend/domain/like/ApiV1LikeControllerTest.java
  backend/src/test/resources/sql/init.sql
Labels: enhancement

#77 [FEAT] [FE] : B-05 #75
  backend/src/main/java/com/backend/global/security/SecurityConfig.java
  frontend/.env.local
  frontend/next-env.d.ts
  frontend/src/api/axios.ts
  frontend/src/app/admin/category/page.tsx
  frontend/src/app/job-posting/page.tsx
  frontend/src/app/post/write/page.tsx
  frontend/src/app/posts/write/page.tsx
  frontend/src/types/jobPosting.ts
  frontend/src/utils/date.ts
Labels: frontend, layout

#73 [FEAT] B-05 #61
  backend/src/main/java/com/backend/domain/post/controller/ApiV1PostController.java
  backend/src/main/java/com/backend/domain/post/repository/PostRepository.java
  backend/src/main/java/com/backend/domain/post/service/PostService.java
  backend/src/main/java/com/backend/global/exception/GlobalErrorCode.java
  backend/src/main/java/com/backend/global/response/GenericResponse.java
  backend/src/test/java/com/backend/domain/post/PostControllerTest.java
  backend/src/test/java/com/backend/domain/post/PostRepositoryTest.java
Labels: enhancement

#79 [FEAT] [FE] : B-06FE #78
  backend/src/main/java/com/backend/domain/post/controller/ApiV1PostController.java
  backend/src/test/java/com/backend/domain/post/PostControllerTest.java
  frontend/src/app/post/[id]/page.tsx
Labels: frontend, layout

#76 Feature/J-02
  backend/src/main/java/com/backend/domain/jobposting/dto/JobPostingDetailResponse.java
  backend/src/main/java/com/backend/domain/jobposting/entity/JobPosting.java
  backend/src/main/java/com/backend/domain/like/dto/LikeCreateResponse.java
  backend/src/main/java/com/backend/domain/like/repository/LikeJpaRepository.java
  backend/src/main/java/com/backend/domain/like/repository/LikeRepository.java
  backend/src/main/java/com/backend/domain/like/repository/LikeRepositoryImpl.java
  backend/src/main/java/com/backend/domain/voter/controller/ApiV1VoterController.java
  backend/src/main/java/com/backend/domain/voter/domain/VoterType.java
  backend/src/main/java/com/backend/domain/voter/dto/VoterCreateRequest.java
  backend/src/main/java/com/backend/domain/voter/dto/VoterCreateResponse.java
  backend/src/main/java/com/backend/domain/voter/entity/Voter.java
  backend/src/main/java/com/backend/domain/voter/repository/VoterJpaRepository.java
  backend/src/main/java/com/backend/domain/voter/repository/VoterRepository.java
  backend/src/main/java/com/backend/domain/voter/repository/VoterRepositoryImpl.java
  backend/src/main/java/com/backend/domain/voter/service/VoterService.java
  backend/src/main/java/com/backend/global/baseentity/BaseInitData.java
  backend/src/main/java/com/backend/global/exception/GlobalErrorCode.java
  backend/src/main/java/com/backend/global/security/SecurityConfig.java
  backend/src/test/java/com/backend/domain/user/ApiV1UserControllerTest.java
  backend/src/test/java/com/backend/domain/voter/ApiV1VoterControllerTest.java
  backend/src/test/resources/application-test.yml
  backend/src/test/resources/sql/delete.sql
  backend/src/test/resources/sql/init.sql
Labels: refactoring

#90 [FEAT] [FE] : B-07FE #86
  backend/src/main/java/com/backend/domain/post/dto/PostResponseDto.java
  frontend/package-lock.json
  frontend/package.json
  frontend/src/app/chat/page.tsx
  frontend/src/app/page.tsx
  frontend/src/app/post/[id]/page.tsx
  frontend/src/app/post/page.tsx
  frontend/src/app/users/[id]/page.tsx
  frontend/src/components/Header.tsx
Labels: frontend, layout

#71 [FEAT] CG-04 #45
  backend/src/main/java/com/backend/domain/category/controller/CategoryController.java
  backend/src/main/java/com/backend/domain/category/entity/Category.java
  backend/src/main/java/com/backend/domain/category/repository/CategoryRepository.java
  backend/src/main/java/com/backend/domain/category/service/CategoryService.java
  backend/src/main/java/com/backend/global/security/SecurityConfig.java
  backend/src/test/java/com/backend/domain/category/CategoryControllerTest.java
Labels: enhancement

#89 [FEAT] B-04 #62
  backend/src/main/java/com/backend/domain/post/controller/ApiV1PostController.java
  backend/src/main/java/com/backend/domain/post/dto/PostRequestDto.java
  backend/src/main/java/com/backend/domain/post/entity/Post.java
  backend/src/main/java/com/backend/domain/post/service/PostService.java
  backend/src/main/java/com/backend/global/exception/GlobalErrorCode.java
  backend/src/test/java/com/backend/domain/post/PostControllerTest.java
  backend/src/test/java/com/backend/domain/post/PostRepositoryTest.java
  backend/src/test/resources/sql/init.sql
Labels: enhancement

#88 [FEAT] Feature/J-02
  backend/src/main/java/com/backend/domain/jobposting/controller/ApiV1JobPostingController.java
  backend/src/main/java/com/backend/domain/jobposting/dto/JobPostingDetailResponse.java
  backend/src/main/java/com/backend/domain/jobposting/dto/JobPostingPageResponse.java
  backend/src/main/java/com/backend/domain/jobposting/repository/JobPostingQueryRepository.java
  backend/src/main/java/com/backend/domain/jobposting/repository/JobPostingRepository.java
  backend/src/main/java/com/backend/domain/jobposting/repository/JobPostingRepositoryImpl.java
  backend/src/main/java/com/backend/domain/jobposting/service/JobPostingService.java
  backend/src/main/java/com/backend/domain/jobskill/dto/JobSkillResponse.java
  backend/src/main/java/com/backend/global/security/SecurityConfig.java
  backend/src/test/java/com/backend/domain/jobposting/ApiV1JobPostingControllerTest.java
  backend/src/test/java/com/backend/domain/voter/ApiV1VoterControllerTest.java
Labels: enhancement

#93 [FEAT] [FE] : R-00FE #91
  frontend/src/app/admin/profile/page.tsx
  frontend/src/app/post/[id]/page.tsx
  frontend/src/app/posts/page.tsx
Labels: frontend, layout

#98 [FEAT]B-02 #67
  backend/src/main/java/com/backend/domain/category/entity/Category.java
  backend/src/main/java/com/backend/domain/post/controller/ApiV1PostController.java
  backend/src/main/java/com/backend/domain/post/dto/PostResponseDto.java
  backend/src/main/java/com/backend/domain/post/entity/Post.java
  backend/src/main/java/com/backend/domain/post/service/PostService.java
  backend/src/main/java/com/backend/global/exception/GlobalErrorCode.java
  backend/src/test/java/com/backend/domain/post/PostControllerTest.java
  backend/src/test/java/com/backend/domain/post/PostRepositoryTest.java
Labels: enhancement

#85 [FEAT] R-01
  backend/src/main/java/com/backend/domain/chat/dto/response/ChatsInPost.java
  backend/src/main/java/com/backend/domain/chat/service/ChatService.java
  backend/src/main/java/com/backend/domain/post/controller/ApiV1PostController.java
  backend/src/main/java/com/backend/domain/post/dto/PostResponseDto.java
  backend/src/main/java/com/backend/domain/post/entity/Post.java
  backend/src/main/java/com/backend/domain/post/service/PostService.java
  backend/src/main/java/com/backend/domain/recruitmentUser/controller/ApiV1RecruitmentAuthorController.java
  backend/src/main/java/com/backend/domain/recruitmentUser/controller/ApiV1RecruitmentUserController.java
  backend/src/main/java/com/backend/domain/recruitmentUser/dto/request/AuthorRequest.java
  backend/src/main/java/com/backend/domain/recruitmentUser/dto/response/RecruitmentPostResponse.java
  backend/src/main/java/com/backend/domain/recruitmentUser/dto/response/RecruitmentUserDetail.java
  backend/src/main/java/com/backend/domain/recruitmentUser/dto/response/RecruitmentUserPageResponse.java
  backend/src/main/java/com/backend/domain/recruitmentUser/entity/RecruitmentUser.java
  backend/src/main/java/com/backend/domain/recruitmentUser/entity/RecruitmentUserStatus.java
  backend/src/main/java/com/backend/domain/recruitmentUser/repository/RecruitmentUserRepository.java
  backend/src/main/java/com/backend/domain/recruitmentUser/service/RecruitmentAuthorService.java
  backend/src/main/java/com/backend/domain/recruitmentUser/service/RecruitmentUserService.java
  backend/src/main/java/com/backend/global/exception/GlobalErrorCode.java
  backend/src/main/java/com/backend/global/security/SecurityConfig.java
  backend/src/main/java/com/backend/global/security/custom/CustomUserDetails.java
  backend/src/main/java/com/backend/global/security/filter/JwtAuthorizationFilter.java
  backend/src/main/java/com/backend/standard/util/SecurityUtil.java
  backend/src/test/java/com/backend/domain/chat/ChatControllerTest.java
  backend/src/test/java/com/backend/domain/post/PostRepositoryTest.java
  backend/src/test/java/com/backend/domain/recruitment/RecruitmentAuthorTest.java
  backend/src/test/java/com/backend/domain/recruitment/RecruitmentUserTest.java
  backend/src/test/java/com/backend/global/scheduler/SchedulerTest.java
  backend/src/test/resources/sql/delete.sql
  backend/src/test/resources/sql/init.sql
  backend/src/test/resources/sql/initRecruitmentUser.sql
Labels: enhancement

#95 [FEAT]J-05
  backend/src/main/java/com/backend/domain/jobposting/controller/ApiV1JobPostingController.java
  backend/src/main/java/com/backend/domain/jobposting/repository/JobPostingQueryRepository.java
  backend/src/main/java/com/backend/domain/jobposting/repository/JobPostingRepository.java
  backend/src/main/java/com/backend/domain/jobposting/repository/JobPostingRepositoryImpl.java
  backend/src/main/java/com/backend/domain/jobposting/service/JobPostingService.java
  backend/src/main/java/com/backend/domain/post/controller/ApiV1PostController.java
  backend/src/main/java/com/backend/domain/voter/controller/ApiV1VoterController.java
  backend/src/main/java/com/backend/domain/voter/domain/VoterType.java
  backend/src/main/java/com/backend/domain/voter/dto/VoterCreateRequest.java
  backend/src/main/java/com/backend/domain/voter/dto/VoterCreateResponse.java
  backend/src/main/java/com/backend/global/security/SecurityConfig.java
  backend/src/main/resources/templates/application-dev.yml
  backend/src/test/java/com/backend/domain/jobposting/ApiV1JobPostingControllerTest.java
Labels: enhancement

#99 [FEAT] M-01
  backend/build.gradle
  backend/src/main/java/com/backend/BackendApplication.java
  backend/src/main/java/com/backend/global/config/AsyncConfig.java
  backend/src/main/java/com/backend/global/config/MailConfig.java
  backend/src/main/java/com/backend/global/mail/service/MailService.java
  backend/src/main/java/com/backend/global/mail/service/MailServiceImpl.java
  backend/src/main/java/com/backend/global/mail/util/EmailTemplateMaker.java
  backend/src/main/java/com/backend/global/mail/util/MailSender.java
  backend/src/main/java/com/backend/global/mail/util/MailSenderImpl.java
  backend/src/main/java/com/backend/global/mail/util/TemplateMaker.java
  backend/src/main/java/com/backend/global/mail/util/TemplateName.java
  backend/src/main/resources/mail-templates/recruitment-chat-template.html
  backend/src/test/resources/application-test.yml
Labels: enhancement

#105 [FEAT] [FE] : R-01FE #94
  backend/src/main/java/com/backend/domain/recruitmentUser/service/RecruitmentAuthorService.java
  backend/src/main/java/com/backend/domain/user/dto/response/UserGetProfileResponse.java
  backend/src/main/java/com/backend/domain/user/entity/SiteUser.java
  frontend/src/api/axios.ts
  frontend/src/api/jobPosting.ts
  frontend/src/api/post.ts
  frontend/src/app/job-posting/[id]/page.tsx
  frontend/src/app/job-posting/page.tsx
  frontend/src/app/job-postings/[id]/page.tsx
  frontend/src/app/job-postings/page.tsx
  frontend/src/app/page.tsx
  frontend/src/app/post/[id]/page.tsx
  frontend/src/app/post/write/page.tsx
  frontend/src/app/recruitment/[postId]/page.tsx
  frontend/src/app/users/[id]/page.tsx
  frontend/src/components/recruitment/RecruitmentButton.tsx
  frontend/src/pages/profile/index.tsx
  frontend/src/types/jobPosting.ts
Labels: frontend, layout

#111 [FEAT] [FE] : R-02FE #106
  backend/src/main/java/com/backend/domain/user/entity/SiteUser.java
  frontend/next-env.d.ts
  frontend/src/api/axios.ts
  frontend/src/app/admin/login/page.tsx
  frontend/src/app/job-posting/[id]/page.tsx
  frontend/src/app/job-posting/page.tsx
  frontend/src/app/login/page.tsx
  frontend/src/app/post/[id]/page.tsx
  frontend/src/app/post/write/page.tsx
Labels: frontend, layout

#108 Feature/V-01
  backend/src/main/java/com/backend/domain/voter/controller/ApiV1VoterController.java
  backend/src/main/java/com/backend/domain/voter/repository/VoterJpaRepository.java
  backend/src/main/java/com/backend/domain/voter/repository/VoterRepository.java
  backend/src/main/java/com/backend/domain/voter/repository/VoterRepositoryImpl.java
  backend/src/main/java/com/backend/domain/voter/service/VoterService.java
  backend/src/main/java/com/backend/global/exception/GlobalErrorCode.java
  backend/src/main/java/com/backend/global/security/SecurityConfig.java
  backend/src/test/java/com/backend/domain/voter/ApiV1VoterControllerTest.java
  backend/src/test/resources/sql/init.sql
Labels: enhancement

#113 Feature/B-02
  backend/src/main/java/com/backend/domain/category/domain/CategoryName.java
  backend/src/main/java/com/backend/domain/category/entity/Category.java
  backend/src/main/java/com/backend/domain/comment/service/CommentService.java
  backend/src/main/java/com/backend/domain/post/controller/ApiV1FreePostController.java
  backend/src/main/java/com/backend/domain/post/controller/ApiV1FreePostController2.java
  backend/src/main/java/com/backend/domain/post/controller/ApiV1PostController.java
  backend/src/main/java/com/backend/domain/post/controller/ApiV1RecruitmentPostController.java
  backend/src/main/java/com/backend/domain/post/controller/ApiV1RecruitmentPostController2.java
  backend/src/main/java/com/backend/domain/post/conveter/PostConverter.java
  backend/src/main/java/com/backend/domain/post/dto/FreePostRequest.java
  backend/src/main/java/com/backend/domain/post/dto/PostCreateResponse.java
  backend/src/main/java/com/backend/domain/post/dto/PostPageResponse.java
  backend/src/main/java/com/backend/domain/post/dto/PostRequestDto.java
  backend/src/main/java/com/backend/domain/post/dto/PostResponse.java
  backend/src/main/java/com/backend/domain/post/dto/PostResponseDto.java
  backend/src/main/java/com/backend/domain/post/dto/RecruitmentPostRequest.java
  backend/src/main/java/com/backend/domain/post/entity/Post.java
  backend/src/main/java/com/backend/domain/post/entity/RecruitmentStatus.java
  backend/src/main/java/com/backend/domain/post/repository/PostJpaRepository.java
  backend/src/main/java/com/backend/domain/post/repository/PostQueryRepository.java
  backend/src/main/java/com/backend/domain/post/repository/PostRepository.java
  backend/src/main/java/com/backend/domain/post/repository/PostRepository2.java
  backend/src/main/java/com/backend/domain/post/repository/PostRepositoryImpl.java
  backend/src/main/java/com/backend/domain/post/service/FreePostService.java
  backend/src/main/java/com/backend/domain/post/service/PostService.java
  backend/src/main/java/com/backend/domain/post/service/PostService2.java
  backend/src/main/java/com/backend/domain/post/service/RecruitmentPostService.java
  backend/src/main/java/com/backend/domain/post/util/PostSearchCondition.java
  backend/src/main/java/com/backend/domain/recruitmentUser/controller/ApiV1RecruitmentUserController.java
  backend/src/main/java/com/backend/domain/recruitmentUser/dto/response/RecruitmentPostResponse.java
  backend/src/main/java/com/backend/domain/recruitmentUser/service/RecruitmentAuthorService.java
  backend/src/main/java/com/backend/domain/recruitmentUser/service/RecruitmentUserService.java
  backend/src/main/java/com/backend/domain/voter/entity/Voter.java
  backend/src/main/java/com/backend/domain/voter/repository/VoterJpaRepository.java
  backend/src/main/java/com/backend/domain/voter/repository/VoterRepository.java
  backend/src/main/java/com/backend/domain/voter/repository/VoterRepositoryImpl.java
  backend/src/main/java/com/backend/domain/voter/service/VoterService.java
  backend/src/main/java/com/backend/global/exception/GlobalErrorCode.java
  backend/src/main/java/com/backend/global/scheduler/service/PostSchedulerService.java
  backend/src/main/java/com/backend/global/security/SecurityConfig.java
  backend/src/test/java/com/backend/domain/post/PostControllerTest.java
  backend/src/test/java/com/backend/domain/post/PostRepositoryTest.java
  backend/src/test/resources/sql/init.sql
Labels: enhancement, refactoring

#110 [FEAT] R-02 #101
  backend/src/main/java/com/backend/domain/post/conveter/PostConverter.java
  backend/src/main/java/com/backend/domain/post/dto/PostResponse.java
  backend/src/main/java/com/backend/domain/post/dto/PostResponseDto.java
  backend/src/main/java/com/backend/domain/post/entity/Post.java
  backend/src/main/java/com/backend/domain/post/repository/PostQueryRepository.java
  backend/src/main/java/com/backend/domain/post/repository/PostRepository.java
  backend/src/main/java/com/backend/domain/post/repository/PostRepositoryImpl.java
  backend/src/main/java/com/backend/domain/post/service/PostService.java
  backend/src/main/java/com/backend/domain/post/service/RecruitmentPostService.java
  backend/src/main/java/com/backend/domain/recruitmentUser/dto/response/RecruitmentPostResponse.java
  backend/src/main/java/com/backend/domain/recruitmentUser/entity/RecruitmentUser.java
  backend/src/main/java/com/backend/domain/recruitmentUser/repository/RecruitmentUserRepository.java
  backend/src/main/java/com/backend/domain/recruitmentUser/service/RecruitmentAuthorService.java
  backend/src/main/java/com/backend/domain/recruitmentUser/service/RecruitmentUserService.java
  backend/src/test/java/com/backend/domain/recruitment/RecruitmentMailTest.java
  backend/src/test/java/com/backend/domain/recruitment/RecruitmentUserTest.java
  backend/src/test/resources/sql/init.sql
  backend/src/test/resources/sql/initRecruitmentUser.sql
Labels: enhancement

#104 [Refactor]CH-01
  backend/src/main/java/com/backend/domain/chat/controller/ApiV1ChatController.java
  backend/src/main/java/com/backend/domain/chat/controller/ApiV1ChatMessageController.java
  backend/src/main/java/com/backend/domain/chat/controller/ChatControllerV1.java
  backend/src/main/java/com/backend/domain/chat/handler/StompHandler.java
  backend/src/main/java/com/backend/domain/chat/service/ChatService.java
  backend/src/main/java/com/backend/domain/recruitmentUser/repository/RecruitmentUserRepository.java
  backend/src/main/java/com/backend/global/config/WebSocketConfig.java
  backend/src/main/java/com/backend/global/security/SecurityConfig.java
  backend/src/main/java/com/backend/standard/util/ExtractUtil.java
  backend/src/main/java/com/backend/standard/util/SecurityUtil.java
  backend/src/main/resources/mail-templates/index.html
  backend/src/main/resources/templates/index.html
  backend/src/test/java/com/backend/domain/chat/ChatControllerTest.java
Labels: refactoring

#114 [FEAT] [FE] : R-02FE #112
  backend/src/main/java/com/backend/domain/post/service/RecruitmentPostService.java
  backend/src/main/java/com/backend/global/baseentity/BaseInitData.java
  frontend/src/app/job-posting/[id]/page.tsx
  frontend/src/app/job-posting/page.tsx
  frontend/src/app/job-posting/voted/page.tsx
  frontend/src/app/page.tsx
  frontend/src/app/post/[id]/edit/page.tsx
  frontend/src/app/post/[id]/page.tsx
  frontend/src/app/post/page.tsx
  frontend/src/app/post/recruitment/[id]/edit/page.tsx
  frontend/src/app/post/recruitment/write/page.tsx
  frontend/src/app/post/write/page.tsx
  frontend/src/types/category.ts
  frontend/src/types/post.ts
  frontend/src/types/recruitmentStatus.ts
Labels: frontend, layout

#117 [FEAT] [FE] : R-04FE #115
  backend/src/main/java/com/backend/domain/jobposting/repository/JobPostingJpaRepository.java
  backend/src/main/java/com/backend/domain/post/repository/PostQueryRepository.java
  backend/src/main/java/com/backend/domain/recruitmentUser/controller/ApiV1RecruitmentUserController.java
  backend/src/main/java/com/backend/domain/recruitmentUser/entity/RecruitmentUserStatus.java
  backend/src/main/java/com/backend/domain/recruitmentUser/service/RecruitmentUserService.java
  backend/src/main/java/com/backend/global/exception/GlobalErrorCode.java
  backend/src/main/java/com/backend/global/security/SecurityConfig.java
  backend/src/test/java/com/backend/domain/recruitment/RecruitmentUserTest.java
  frontend/src/app/page.tsx
  frontend/src/app/post/[id]/edit/page.tsx
  frontend/src/app/post/[id]/page.tsx
  frontend/src/app/post/page.tsx
  frontend/src/app/post/recruitment/[id]/edit/page.tsx
  frontend/src/app/users/[id]/page.tsx
Labels: frontend, layout

#124 [REFACTOR] G-01
  backend/src/main/java/com/backend/domain/category/controller/CategoryController.java
  backend/src/main/java/com/backend/domain/chat/controller/ApiV1ChatController.java
  backend/src/main/java/com/backend/domain/comment/controller/ApiV1CommentController.java
  backend/src/main/java/com/backend/domain/jobposting/controller/ApiV1JobPostingController.java
  backend/src/main/java/com/backend/domain/post/controller/ApiV1FreePostController.java
  backend/src/main/java/com/backend/domain/post/controller/ApiV1PostController.java
  backend/src/main/java/com/backend/domain/post/controller/ApiV1RecruitmentPostController.java
  backend/src/main/java/com/backend/domain/recruitmentUser/controller/ApiV1RecruitmentAuthorController.java
  backend/src/main/java/com/backend/domain/recruitmentUser/controller/ApiV1RecruitmentUserController.java
  backend/src/main/java/com/backend/domain/user/controller/ApiV1UserController.java
  backend/src/main/java/com/backend/domain/voter/controller/ApiV1VoterController.java
  backend/src/main/java/com/backend/global/advice/GlobalControllerAdvice.java
  backend/src/main/java/com/backend/global/response/GenericResponse.java
  backend/src/main/java/com/backend/global/security/SecurityConfig.java
  backend/src/main/java/com/backend/global/security/filter/JwtAuthenticationFilter.java
  backend/src/main/java/com/backend/global/security/filter/JwtAuthorizationFilter.java
  backend/src/main/java/com/backend/global/security/handler/JwtLogoutSuccessHandler.java
  backend/src/main/java/com/backend/global/security/handler/OAuth2LoginFailureHandler.java
  backend/src/main/java/com/backend/global/security/handler/OAuth2LoginSuccessHandler.java
Labels: refactoring
